# Config file for Majora's Mask NTSC 1.0 Recompilation.

[input]
entrypoint = 0x80080000
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
relocatable_sections_path = "overlays.us.rev1.txt"
elf_path = "mm-n64-us.elf"
