# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_recomp_better_double_sot"

# Version of this mod.
version = "1.0.1"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Better Song of Double Time"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
This mod adds hour selection for Song of Double Time."""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Hour selection for Song of Double Time."

# Authors of this mod.
authors = [ "danielryb" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
    "mm_recomp_message_hooks:2.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_recomp_better_double_sot"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [
    "thumb.dds"
]


## Config options:

[[manifest.config_options]]
id = "accept_analog_input"
name = "Accept Analog Stick Input"
description = """Enables input from analog stick's X-axis (left and right) during the hour selection.
"""
type = "Enum"
options = [
    "on",
    "off"
]
default = "on"

[[manifest.config_options]]
id = "accept_dpad_input"
name = "Accept D-Pad Input"
description = """Enables input from D-pad left (special item 2) and right (special item 4) buttons during the hour selection.
"""
type = "Enum"
options = [
    "on",
    "off"
]
default = "on"

[[manifest.config_options]]
id = "accept_zr_input"
name = "Accept Z/R Input"
description = """Enables input from Z (target) and R (shield) buttons during the hour selection.
"""
type = "Enum"
options = [
    "on",
    "off"
]
default = "on"

[[manifest.config_options]]
id = "skip_dsot_cutscene"
name = "Skip Cutscene"
description = """Disables the Song of Double Time cutscene.
"""
type = "Enum"
options = [
    "on",
    "off"
]
default = "off"